openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-kubernetes-postgresql
components:
  schemas:
    variables:
      required: []
      type: object
      properties:
        context:
          title: Context
          type: object
          description: |
            Receive contextual information. When Walrus deploys, Walrus will inject specific contextual information into this field.

            Examples:
            ```
            context:
              project:
                name: string
                id: string
              environment:
                name: string
                id: string
              resource:
                name: string
                id: string
            ```
          default: {}
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            hidden: true
            order: 1
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.

            Examples:
            ```
            infrastructure:
              namespace: string, optional
              image_registry: string, optional
              domain_suffix: string, optional
            ```
          default: {}
          properties:
            domain_suffix:
              description: |
                Specify the domain name of the Kubernetes cluster.
              default: cluster.local
              title: Domain Suffix
              type: string
              x-walrus-ui:
                order: 3
            image_registry:
              description: |
                Specify the image registry to pull the bitnami/postgresql image, default is `registry-1.docker.io`.
              default: registry-1.docker.io
              title: Image Registry
              type: string
              x-walrus-ui:
                order: 2
            namespace:
              title: Namespace
              type: string
              x-walrus-ui:
                hidden: true
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        architecture:
          title: Architecture
          type: string
          description: |
            Specify the deployment architecture, select from standalone or replication.
          default: standalone
          enum:
          - standalone
          - replication
          x-walrus-ui:
            group: Basic
            order: 3
        replication_readonly_replicas:
          title: Replication Readonly Replicas
          type: number
          description: |
            Specify the number of read-only replicas under the replication deployment.
          default: 1
          enum:
          - 1
          - 2
          - 3
          x-walrus-ui:
            group: Basic
            order: 4
            showIf: architecture=replication
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://hub.docker.com/r/bitnami/postgresql/tags.
          default: "13"
          x-walrus-ui:
            group: Basic
            order: 5
        database:
          title: Database
          type: string
          description: |
            Specify the database name.
          default: mydb
          x-walrus-ui:
            group: Basic
            order: 6
        username:
          title: Username
          type: string
          description: |
            Specify the account username.
          default: rdsuser
          x-walrus-ui:
            group: Basic
            order: 7
        password:
          title: Password
          type: string
          description: |
            Specify the account password. If not specified, it will generate a random password.
          x-walrus-ui:
            group: Basic
            order: 8
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.

            Examples:
            ```
            resources:
              cpu: number, optional
              memory: number, optional       # in megabyte
            ```
          default:
            cpu: 0.25
            memory: 256
          required:
          - cpu
          - memory
          properties:
            cpu:
              description: |
                Specify the cpu resources. Unit is core.
              title: Cpu(Core)
              type: number
              x-walrus-ui:
                order: 1
            memory:
              description: |
                Specify the memory resources. Unit is megabyte.
              title: Memory(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 9
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.

            Examples:
            ```
            storage:                         # convert to empty_dir volume or dynamic volume claim template
              class: string, optional
              size: number, optional         # in megabyte
            ```
          properties:
            class:
              description: |
                Specify the storage class. If not specified, it will use the default provisioner.
              title: Class
              type: string
              x-walrus-ui:
                order: 1
            size:
              description: |
                Specify the storage size. Unit is megabyte.
              default: 20480
              title: Size(MiB)
              type: number
              x-walrus-ui:
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 10
        seeding:
          title: Seeding
          type: object
          description: "Specify the configuration to seed the database at first-time
            creating.\n\nSeeding increases the startup time waiting and also needs
            proper permission, \nlike root account.\n\nExamples:\n```\nseeding:\n
            \ type: url/text\n  url:                           # store the content
            to a volume\n    location: string\n    storage:                     #
            convert to dynamic volume claim template\n      class: string, optional\n
            \     size: number, optional     # in megabyte\n  text:                          #
            store the content to a configmap\n    content: string\n```\n"
          properties:
            text:
              description: |
                Configure database seeding from text.
              properties:
                content:
                  description: |
                    Specify the SQL statements to seed the database.
                  title: Content
                  type: string
              required:
              - content
              title: Text
              type: object
              x-walrus-ui:
                colSpan: 12
                group: Basic
                showIf: type=text
                order: 2
            type:
              description: |
                Specify the seeding approach, select from url or text.
              default: url
              enum:
              - url
              - text
              title: Type
              type: string
              x-walrus-ui:
                order: 1
            url:
              description: |
                Configure database seeding from URL.
              properties:
                location:
                  description: |
                    Specify the URL to download the SQL statements.
                  title: Location
                  type: string
                  x-walrus-ui:
                    order: 1
                storage:
                  description: |
                    Specify a storage to store the downloaded SQL statements.
                  properties:
                    class:
                      description: |
                        Specify the storage class. If not specified, it will use the default provisioner.
                      title: Class
                      type: string
                      x-walrus-ui:
                        order: 1
                    size:
                      description: |
                        Specify the storage size. Unit is megabyte.
                      default: 10240
                      title: Size(MiB)
                      type: number
                      x-walrus-ui:
                        order: 2
                  title: Storage
                  type: object
                  x-walrus-ui:
                    colSpan: 12
                    order: 2
              required:
              - location
              title: Url
              type: object
              x-walrus-ui:
                colSpan: 12
                showIf: type=url
                order: 2
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 11
